# Basic Site Info
title: "Yichen Lou (娄怡晨)"
email: "louyichen19@outlook.com"
description: >-
  Postdoctoral Fellow in Statistics. Research interests include survival analysis, biased sampling, missing data, causal inference, change point, competing risks, and transfer learning.

# Remote theme for acad-homepage
remote_theme: alshedivat/al-folio

# Site Author
name: "Yichen Lou"
affiliation: 
  - "Postdoctoral Fellow, Chinese University of Hong Kong"
  - "Incoming Postdoctoral Fellow, Nanyang Technological University, Singapore"
position: "Postdoctoral Fellow"
interests: 
  - Survival analysis
  - Biased sampling
  - Missing data
  - Causal inference
  - Change point
  - Competing risks
  - Transfer learning
email: "louyichen19@outlook.com"

# Contact (optional)
address: "Singapore & Hong Kong"
phone: "+86 188 4406 8624"

# Social & Links (fill as needed)
github_username: "YOUR_GITHUB_USERNAME"  # replace with your GitHub username
google_scholar: "YOUR_GOOGLE_SCHOLAR_URL"  # replace with your Scholar link

# Navbar menu
navbar_links:
  Home: "about"
  Publications: "publications"
  Invited Talks: "talks"
  Education: "education"
  Internships: "internships"
  Contact: "contact"

# Plugins
plugins:
  - jekyll-remote-theme

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Exclude files from build
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules

# Footer
footer_text: "© Yichen Lou. Powered by acad-homepage and GitHub Pages."
